name: config-cluster

services:
  config-1:
    build:
      context: ./
    container_name: config-1
    ports:
      - "8084:8084"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1" ]
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://host.docker.internal:8761/eureka/,http://host.docker.internal:8762/eureka/
    restart: unless-stopped

  config-2:
    build:
      context: ./
    container_name: config-2
    ports:
      - "8085:8084"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1" ]
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://host.docker.internal:8761/eureka/,http://host.docker.internal:8762/eureka/
    restart: unless-stopped