server:
  port: 8084

spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      server:
        git:
          uri: https://github.com/franklinclf/nexus-spring-cloud-config-data.git
          search-paths: '{application}/{profile}'
          default-label: main
          clone-on-start: true
      fail-fast: true
      retry:
        max-attempts: 6
        multiplier: 1.1
        max-interval: 2000
        initial-interval: 1000

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-1:8761/eureka/,http://eureka-2:8762/eureka/}
    register-with-eureka: true
    fetch-registry: false
    instance-info-replication-interval-seconds: 5
  instance:
    instance-id: config-${REPLICA_ID:1}
    hostname: config-${REPLICA_ID:1}
    appname: config

management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
    access:
      default: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: http://host.docker.internal:9411/api/v2/spans