server:
  port: ${PORT:8888}
  shutdown: graceful

eureka:
  instance:
    instance-id: ${spring.application.name}-${REPLICA_ID:1}
    hostname: ${spring.application.name}-${REPLICA_ID:1}
    app-group-name: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${EUREKA_REPLICAS:http://eureka-1:8761/eureka,http://eureka-2:8762/eureka,http://eureka-3:8763/eureka}
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 15

spring:
  cloud:
    config:
      discovery:
        service-id: config
      server:
        git:
          search-paths: '{application}/{profile}'
          clone-on-start: true
          uri: ${GIT_URL:https://github.com/franklinclf/nexus-spring-cloud-config-data.git}
          force-pull: true
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
    access:
      default: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
        step: 5s
  logging:
    export:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}-${REPLICA_ID:1}
    distribution:
      percentiles-histogram:
        enabled: true
        http.server.requests: true
        http.client.requests: true
    enable:
      jvm: true
      process: true
      system: true
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: http://zipkin:9411/api/v2/spans
  endpoint:
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true